#######################################################################################
# Book settings
title : Environmental Simulation Modelling
author: Tristan Salles
copyright: "2020-2022"  # Copyright year to be placed in the footer
logo: 'qe-logo-large.png'

# Launch button settings
repository:
  url                         : https://github.com/TristanSalles/EnviReef
  path_to_book                : "book"
  branch                      : main

#######################################################################################
# Execution settings
execute:
  execute_notebooks           : cache

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar         : false
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  extra_footer: |
    <p>
    <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">
      <img align="right" class="margin" src="https://mirrors.creativecommons.org/presskit/buttons/88x31/svg/by.svg" width="88px">
    </a>
    These lecture notes and exercises are licensed under a <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">Creative Commons Attribution 4.0 International (CC BY 4.0) license</a>.
    <br>
    &copy; Copyright 2020-2022.
    </p>

# #######################################################################################
# Interact link settings
notebook_interface            : "notebook"

launch_buttons:
  notebook_interface: "jupyterlab"

binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"

latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
   - docs/ref.bib

execute:
  execute_notebooks: auto
  allow_errors: true
